# Generated by Django 2.1 on 2018-03-07 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clsmanagent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(),
        ),
    ]
